In [2]:
import numpy as np
import json

In [3]:
file = open("numsPixelReference.txt")
file_text = "".join(file.readlines())
file_text.split("\n\n")
nums = file_text.split("\n\n")
nums = [l.split("\n") for l in nums]

for i in range(len(nums)):
    nums[i][0] = nums[i][0][1:]
    nums[i][len(nums[i]) - 1] = nums[i][len(nums[i]) - 1][:-1]
#     nums[i] = nums[i][:-1]
    
    for j in range(len(nums[i])):
        nums[i][j] = nums[i][j].replace(".", ",").replace(" ", "")
        nums[i][j] = nums[i][j][:-2] + nums[i][j][-1:]
        nums[i][j] = json.loads(nums[i][j])
    
nums = np.array(nums)

print(sum_mat)

[[ 2.  2.  7.  7.  8.  8. 10. 10. 10. 10.  9.  9.  2.  2.]
 [ 2.  2.  7.  7.  8.  8. 10. 10. 10. 10.  9.  9.  2.  2.]
 [ 7.  7.  8.  8.  3.  3.  2.  2.  3.  3.  7.  7.  6.  6.]
 [ 7.  7.  8.  8.  3.  3.  2.  2.  3.  3.  7.  7.  6.  6.]
 [ 5.  5.  6.  6.  2.  2.  3.  3.  5.  5.  8.  8.  5.  5.]
 [ 5.  5.  6.  6.  2.  2.  3.  3.  5.  5.  8.  8.  5.  5.]
 [ 3.  3.  5.  5.  4.  4.  8.  8.  8.  8.  8.  8.  3.  3.]
 [ 3.  3.  5.  5.  4.  4.  8.  8.  8.  8.  8.  8.  3.  3.]
 [ 4.  4.  5.  5.  4.  4.  4.  4.  2.  2.  7.  7.  7.  7.]
 [ 4.  4.  5.  5.  4.  4.  4.  4.  2.  2.  7.  7.  7.  7.]
 [ 6.  6.  6.  6.  1.  1.  2.  2.  3.  3.  8.  8.  6.  6.]
 [ 6.  6.  6.  6.  1.  1.  2.  2.  3.  3.  8.  8.  6.  6.]
 [ 1.  1.  8.  8.  9.  9.  9.  9.  9.  9.  8.  8.  2.  2.]
 [ 1.  1.  8.  8.  9.  9.  9.  9.  9.  9.  8.  8.  2.  2.]]


In [139]:
def sumMatrix(mats):
    result = np.zeros((14,14))
    for mat in mats:
        result = np.add(result, mat)
    return result

def mask(mat, num):
    def vct(num, target):
        if num != target:
            return 0
        else:
            return num
    
    return np.vectorize(vct)(mat, num)

# mask(sum_mat, 5)

def split(mat, row, col):
    l1 = []
    l2 = []
    
    for m in mat:
        if m[row][col] == 0:
            l1.append(m)
        else:
            l2.append(m)
    
    return l1, l2

# sum_mat[5][8]

l1_0, l1_1 =  split(nums, 5, 8)

# print(sumMatrix(l1_0))
l2_0, l2_1  = split(l1_0, 7, 3) # 2, 3 | 6, 8, 9

l2_2, l2_3 = split(l1_1, 7, 3) # 1, 5, 7 | 0, 4

# print(mask(sumMatrix(l2_1), 1))
# print(mask(sumMatrix(l2_2), 1))
# print()
# print(mask(sumMatrix(l2_1), 1) + mask(sumMatrix(l2_2), 1))

# mask(sumMatrix(l2_1), 2) + mask(sumMatrix(l2_2), 1)
# mask(sumMatrix(l2_1), 1) + mask(sumMatrix(l2_2), 2)
# mask(sumMatrix(l2_1), 2) + mask(sumMatrix(l2_2), 2)

l3_0, l3_1 = split(l2_0, 10, 9) # 2, 3 |
l3_2, l3_3 = split(l2_1, 10, 9) # 6, 8 | 9
l3_4, l3_5 = split(l2_2, 10, 9) # 5, 7 | 1
l3_6, l3_7 = split(l2_3, 10, 9) # 0 | 4

# print(mask(sumMatrix(l3_0), 1))
# print()
# print(mask(sumMatrix(l3_2), 1))# + 
# print()
# print(mask(sumMatrix(l3_4), 1))
# print(mask(mask(sumMatrix(l3_2), 1) + mask(sumMatrix(l3_4), 1), 2))

l4_0, l4_1 = split(l3_0, 2, 11) # | 2, 3
l4_2, l4_3 = split(l3_1, 2, 11) # |
l4_4, l4_5 = split(l3_2, 2, 11) # 6 | 8
l4_6, l4_7 = split(l3_3, 2, 11) # | 9 
l4_8, l4_9 = split(l3_4, 2, 11) # 5 | 7
l4_10, l4_11 = split(l3_5, 2, 11) # 1 | 
l4_12, l4_13 = split(l3_6, 2, 11) # | 0
l4_14, l4_15 = split(l3_7, 2, 11) # | 4

l5_0, l5_1 = split(l4_1, 8, 5) # 3 | 2

In [165]:
pixelRef = {
    "[1, 1, 0, 1, 1]": 0,
    "[1, 0, 1, 0, 0]": 1,
    "[0, 0, 0, 1, 1]": 2,
    "[0, 0, 0, 1, 0]": 3,
    "[1, 1, 1, 1, 1]": 4,
    "[1, 0, 0, 0, 0]": 5,
    "[0, 1, 0, 0, 0]": 6,
    "[1, 0, 0, 1, 1]": 7,
    "[0, 1, 0, 1, 0]": 8,
    "[0, 1, 1, 1, 0]": 9
}

id_pixels = [(5, 8), (7, 3), (10, 9), (2, 11), (8, 5)]

def findNum(mat):
    pixKey = str([mat[px[0]][px[1]] for px in id_pixels])
    if pixKey in pixelRef:
        return pixelRef[pixKey]

findNum(nums[8])

8